/**
 * أكواد أخطاء ثابتة — مصدر الحقيقة الوحيد لشكل `error.code` في كل رد فاشل.
 * أي دومين جديد يحتاج كود مش موجود هنا يضيفه هنا أولًا (مش يخترعه inline).
 */
export enum ErrorCode {
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  NOT_FOUND = 'NOT_FOUND',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  DEVICE_MISMATCH = 'DEVICE_MISMATCH',
  DEVICE_ALREADY_REGISTERED = 'DEVICE_ALREADY_REGISTERED',
  ACCOUNT_BANNED = 'ACCOUNT_BANNED',
  MAINTENANCE_MODE = 'MAINTENANCE_MODE',
  PROFILE_EDIT_LOCKED = 'PROFILE_EDIT_LOCKED',
  DUPLICATE_REFERENCE = 'DUPLICATE_REFERENCE',
  RESET_LIMIT_REACHED = 'RESET_LIMIT_REACHED',
  NOT_ENROLLED = 'NOT_ENROLLED',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
}
